language: c
addons:
  apt:
    packages:
    - libasound2:i386
    - lib32z1
    - lib32bz2-1.0
    - libssl1.0.0:i386
    - libfreetype6:i386
script:
- if [[ ${TRAVIS_BRANCH} == "master" ]]; then make deploy; fi
env:
  global:
    secure: SsXM7Ffo+E8Yl2RJkhzS95BF0gtSZdDzroBvJD4PmHw8KNqoDPypFcGx+4Pi2MRryHSNUEsAF+GAs++E0/Qzl9T8DzavoWlzs/cgZIRARjl5zv6N3p5Tllap0vlfEEG30/jqztPVwYQHmP+3bc8AeliTIRUtYEN4jE1Ye6FAnJarFR6kT5Ba8Z97Oc/il9h+/2Ey7NnzNdpC0ZBsXRubk9zZT7t0cs4AaoXxdmQ1R2Wve4YSrO+gUoXB5W1dPBloJvGMvBK0ApSs1HwNCH5CW0WO7ne00jisJS2nab71AHOGx7tG6wuT4ktCTfqV/7CtgLRJMP6zjaooWKfA1UYK2hWIU/wv5Ma+4MaSWCvuFyKtY2/uaT+bNh3J08IQ0X1gW0Nvbf3w/OSmfKG125ofE5o/YDCpoMuqROokzEfS9QN/cpjMbOPwo8Iy5efx/nIMG2boltXTPBh9t9Q6Nj3UnMKgm9HoucFGNph3AXUnpYO13sgDiqQr85FZ8qe8hUeCT2nS210u7/lmmcU+KME9YriGlI6eeVnPB9jxOfGdpkomuqD0E3fxIW01HUw4j4tENqxwkuYIj+x78XCJ03kKk+B/jNbuvzrcvHNF0iliUYfdBw4f1CoLsVL5hLVmeiU9tlGGMLQRF4QRjwkjQWfhKUdeQJ8dr5P5BXljhvCkSWY=
