language: c
addons:
  apt:
    packages:
    - libasound2:i386
    - lib32z1
    - lib32bz2-1.0
    - libssl1.0.0:i386
    - libfreetype6:i386
script:
- if [[ ${TRAVIS_BRANCH} == "master" ]]; then make deploy; fi
env:
  global:
    secure: k8lGGkbrJFlJw+NcqZdv4fyR9tUU1M9njIAqk4lSWLFQiSHwBLrrrEaYtGMC6f/YwpOTC2iZqb7Bx7rGHNEaSWrnfS8j7/vIH1XtEbGWgr/dcmen4wfAc1FpANO9TYHd4cbT6vZhE/tso0tk/wxryrLzxe0fr10k8dwGu/I2qoRvsMIGtEmB3J3LRA2KScZoNn3FdjaQaflkCRLndtYUNvEtJxifdnExIyDdedgm5Dlxa4O/c6sQAG68YPX6EjbVxtfiwMOhEibE4Ar3m18Ke3PSgNYquybJIrn8jabeSDONnbv3cizZHFANv2xhAicTEsR3/AbjKkDW6oIuThW3rfaegayS9YqmQKYi83AD4cFByLISWnyhwQlExnReODFKmuApUSm0w5F2iBHD+o7AmaY5KENYz0mRTdpQbtH0qEnLFMyNar3YQ4W9Ydnz03KXgNd7lsNQEbocpi2xysErJTMFdVu2hyji6Pz4CxPU+ePFNEBWn9YZS/5PuDGy4RfXU3K84j4GnjJLMd5GLBSUuJwqel1P+lgtjLhFoTUp8afFjKpAR/PpU/0Q3GOu1AjjrviIiXaSXuNIY55mhFG/foHHlVwmxcMeWB51zu11fkmD13o80nGaUx3HHrX1XD/50mAFkeGxI/1b3t1vUPWWRWq2bE7Rf5XBftNUBqK0l0w=
